on: [push]

jobs:
  test:
    runs-on: codeberg-small
    container:
      image: rubylang/ruby:4.0
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends git build-essential libyaml-dev unzip curl
      - run: git clone --depth 1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .

      - run: curl -fsSL https://bun.sh/install | bash
      - run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - run: bundle install
      - run: bun install --frozen-lockfile
      - run: bundle exec bun_bun_bundle build

      - run: bundle exec rspec
      - run: bundle exec rubocop
