name: Deploy

on:
  push:
    branches: [staging, production]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    environment: staging

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/staging

      - name: Tar working tree
        run: tar -cf deploy.tar --exclude=./.git --exclude=./deploy.tar .

      - name: Deploy to Caprover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/production

      - name: Tar working tree
        run: tar -cf deploy.tar --exclude=./.git --exclude=./deploy.tar .

      - name: Deploy to Caprover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
